export const data = {
    plans: [
        {
            id: 1090,
            dataa: '2021-04-02',
            observacao: '',
            id_profissional: null,
            id_paciente: 1333,
            data: '2021-04-02T22:35:19.000Z',
            vr_proteinas: '0.00',
            vr_carboidratos: '0.00',
            vr_lipideos: '0.00',
            vr_calorias: '0.00',
            vr_peso: '0.00',
            nome: 'Por alimento',
            tipo_plano: 0,
            visivel: 1,
            plano_alimentar_refeicaos: [
                {
                    id: 3617,
                    nome: 'Almoço',
                    horario: '12:00:00',
                    id_plano_alimentar: 1090,
                    obs: '',
                    carboidratos: '21.50',
                    lipideos: '8.70',
                    proteinas: '34.90',
                    kcal: '312.80',
                    plano_alimentar_refeicao_alimentos: [
                        {
                            id: 14131,
                            tabela: 'ibge',
                            id_refeicao: 3617,
                            id_alimento: 143,
                            medida_caseira: 'Colhere(s) de sopa',
                            gramas: '60.00',
                            nome: 'Arroz integral, cozido',
                            quantidade_medida: '3.00',
                            plano_alimentar_alimento_equivalentes: [],
                        },
                        {
                            id: 14132,
                            tabela: 'taco',
                            id_refeicao: 3617,
                            id_alimento: 251,
                            medida_caseira: 'Colher(es) de sopa cheia',
                            gramas: '30.00',
                            nome: 'Feijão, carioca, cozido',
                            quantidade_medida: '2.00',
                            plano_alimentar_alimento_equivalentes: [],
                        },
                        {
                            id: 14133,
                            tabela: 'taco',
                            id_refeicao: 3617,
                            id_alimento: 281,
                            medida_caseira: 'Filé(s) médio(s)',
                            gramas: '100.00',
                            nome: 'Frango, peito, sem pele, cozido',
                            quantidade_medida: '1.00',
                            plano_alimentar_alimento_equivalentes: [],
                        },
                        {
                            id: 14134,
                            tabela: 'taco',
                            id_refeicao: 3617,
                            id_alimento: 25,
                            medida_caseira: 'Folha(s) pequena(s)',
                            gramas: '20.00',
                            nome: 'Alface, americano, crua',
                            quantidade_medida: '4.00',
                            plano_alimentar_alimento_equivalentes: [],
                        },
                        {
                            id: 14135,
                            tabela: 'taco',
                            id_refeicao: 3617,
                            id_alimento: 85,
                            medida_caseira: 'Buquê(s)',
                            gramas: '45.00',
                            nome: 'Brócolis, cozido',
                            quantidade_medida: '3.00',
                            plano_alimentar_alimento_equivalentes: [],
                        },
                        {
                            id: 14136,
                            tabela: 'taco',
                            id_refeicao: 3617,
                            id_alimento: 50,
                            medida_caseira: 'Colher(es) de sopa',
                            gramas: '4.00',
                            nome: 'Azeite, de oliva, extra virgem',
                            quantidade_medida: '0.50',
                            plano_alimentar_alimento_equivalentes: [],
                        },
                    ],
                    pa_refeicao_substituta: [],
                    plano_alimentar_refeicao_order: {
                        id: 3612,
                        id_refeicao: 3617,
                        posicao: 3,
                    },
                },
                {
                    id: 3618,
                    nome: 'Jantar',
                    horario: '20:00:00',
                    id_plano_alimentar: 1090,
                    obs: '',
                    carboidratos: '21.50',
                    lipideos: '9.60',
                    proteinas: '34.90',
                    kcal: '313.60',
                    plano_alimentar_refeicao_alimentos: [
                        {
                            id: 14137,
                            tabela: 'taco',
                            id_refeicao: 3618,
                            id_alimento: 223,
                            medida_caseira: 'Colher de sopa',
                            gramas: '48.00',
                            nome: 'Cuscuz, de milho, cozido com sal',
                            quantidade_medida: '4.00',
                            plano_alimentar_alimento_equivalentes: [],
                        },
                        {
                            id: 14138,
                            tabela: 'taco',
                            id_refeicao: 3618,
                            id_alimento: 281,
                            medida_caseira: 'Filé(s) médio(s)',
                            gramas: '100.00',
                            nome: 'Frango, peito, sem pele, cozido',
                            quantidade_medida: '1.00',
                            plano_alimentar_alimento_equivalentes: [],
                        },
                        {
                            id: 14139,
                            tabela: 'ibge',
                            id_refeicao: 3618,
                            id_alimento: 109,
                            medida_caseira: 'Colher(es) de sopa',
                            gramas: '12.00',
                            nome: 'Amêndoa',
                            quantidade_medida: '0.50',
                            plano_alimentar_alimento_equivalentes: [],
                        },
                        {
                            id: 14140,
                            tabela: 'tucunduva',
                            id_refeicao: 3618,
                            id_alimento: 1095,
                            medida_caseira: 'Colher(es) de sobremesa',
                            gramas: '9.00',
                            nome: 'Uva passa',
                            quantidade_medida: '1.00',
                            plano_alimentar_alimento_equivalentes: [],
                        },
                    ],
                    pa_refeicao_substituta: [],
                    plano_alimentar_refeicao_order: {
                        id: 3613,
                        id_refeicao: 3618,
                        posicao: 4,
                    },
                },
                {
                    id: 3619,
                    nome: 'Café da manhã',
                    horario: '07:00:00',
                    id_plano_alimentar: 1090,
                    obs:
                        '<p>Utilize os alimentos listados a cima para fazer um sanduiche natural. Para enriquecer o valor nutricional do mesmo, você pode acrescentar alface, tomate, cenoura ralada, entre outras verduras/legumes. Como acompanhamento, você pode estar ingerindo chás gelados. Sugestões: Chá mate gelado com limão, chá preto com hibisco e limão, chá verde gelado com limão. </p>',
                    carboidratos: '26.00',
                    lipideos: '3.30',
                    proteinas: '5.90',
                    kcal: '154.70',
                    plano_alimentar_refeicao_alimentos: [
                        {
                            id: 14141,
                            tabela: 'tucunduva',
                            id_refeicao: 3619,
                            id_alimento: 614,
                            medida_caseira: 'Fatia(s)',
                            gramas: '120.00',
                            nome: 'Mamão papaia',
                            quantidade_medida: '1.00',
                            plano_alimentar_alimento_equivalentes: [
                                {
                                    id: 6259,
                                    id_refeicao_alimento: 14141,
                                    id_alimento_equivalente: 58,
                                    nome_alimento: 'Banana, nanica, crua',
                                    tabela_equivalente: 'TACO',
                                    nutriente_equivalente: 'Array',
                                    medida_caseira_equivalente:
                                        'Unidade(s) pequena(s)',
                                    gramas_unidade: '86.00',
                                    quantidade: '0.60',
                                    gramas_nutriente: '11.87',
                                },
                                {
                                    id: 6260,
                                    id_refeicao_alimento: 14141,
                                    id_alimento_equivalente: 123,
                                    nome_alimento: 'Ananás ',
                                    tabela_equivalente: 'IBGE',
                                    nutriente_equivalente: 'Array',
                                    medida_caseira_equivalente: 'Rodela(s)',
                                    gramas_unidade: '75.00',
                                    quantidade: '1.20',
                                    gramas_nutriente: '11.37',
                                },
                                {
                                    id: 6261,
                                    id_refeicao_alimento: 14141,
                                    id_alimento_equivalente: 1066,
                                    nome_alimento: 'Jamelão (jamburão) ',
                                    tabela_equivalente: 'IBGE',
                                    nutriente_equivalente: 'Array',
                                    medida_caseira_equivalente: 'Unidade(s)',
                                    gramas_unidade: '5.00',
                                    quantidade: '12.80',
                                    gramas_nutriente: '11.78',
                                },
                                {
                                    id: 6262,
                                    id_refeicao_alimento: 14141,
                                    id_alimento_equivalente: 312,
                                    nome_alimento: 'Jamelão, cru',
                                    tabela_equivalente: 'TACO',
                                    nutriente_equivalente: 'Array',
                                    medida_caseira_equivalente: 'Unidade(s)',
                                    gramas_unidade: '5.00',
                                    quantidade: '23.60',
                                    gramas_nutriente: '11.80',
                                },
                                {
                                    id: 6263,
                                    id_refeicao_alimento: 14141,
                                    id_alimento_equivalente: 649,
                                    nome_alimento: 'Melão',
                                    tabela_equivalente: 'TUCUNDUVA',
                                    nutriente_equivalente: 'Array',
                                    medida_caseira_equivalente: 'Fatia(s)',
                                    gramas_unidade: '90.00',
                                    quantidade: '1.80',
                                    gramas_nutriente: '11.65',
                                },
                            ],
                        },
                        {
                            id: 14142,
                            tabela: 'tucunduva',
                            id_refeicao: 3619,
                            id_alimento: 381,
                            medida_caseira: 'Colher(es) de sopa',
                            gramas: '30.00',
                            nome: 'Farelo de aveia',
                            quantidade_medida: '3.00',
                            plano_alimentar_alimento_equivalentes: [
                                {
                                    id: 6264,
                                    id_refeicao_alimento: 14142,
                                    id_alimento_equivalente: 2874,
                                    nome_alimento: 'Biscoito, aveia, varejo',
                                    tabela_equivalente: 'USDA',
                                    nutriente_equivalente: 'Array',
                                    medida_caseira_equivalente: '1 oz (28,35g)',
                                    gramas_unidade: '28.35',
                                    quantidade: '1.00',
                                    gramas_nutriente: '10.49',
                                },
                                {
                                    id: 6265,
                                    id_refeicao_alimento: 14142,
                                    id_alimento_equivalente: 3213,
                                    nome_alimento: 'Aveia',
                                    tabela_equivalente: 'USDA',
                                    nutriente_equivalente: 'Array',
                                    medida_caseira_equivalente:
                                        'Colher(es) de sopa cheia',
                                    gramas_unidade: '15.00',
                                    quantidade: '1.30',
                                    gramas_nutriente: '10.53',
                                },
                                {
                                    id: 6266,
                                    id_refeicao_alimento: 14142,
                                    id_alimento_equivalente: 2877,
                                    nome_alimento:
                                        'Biscoito, aveia, farinha refrigerada',
                                    tabela_equivalente: 'USDA',
                                    nutriente_equivalente: 'Array',
                                    medida_caseira_equivalente: '1 oz (28,35g)',
                                    gramas_unidade: '28.35',
                                    quantidade: '1.20',
                                    gramas_nutriente: '10.55',
                                },
                            ],
                        },
                        {
                            id: 14143,
                            tabela: 'ibge',
                            id_refeicao: 3619,
                            id_alimento: 109,
                            medida_caseira: 'Unidade(s)',
                            gramas: '2.00',
                            nome: 'Amêndoa',
                            quantidade_medida: '2.00',
                            plano_alimentar_alimento_equivalentes: [],
                        },
                    ],
                    pa_refeicao_substituta: [
                        {
                            id: 178,
                            nome:
                                'Lanche proteico (Vitamina de Whey com fruta) (250 KCAL, 20g CHO, 26g PTN, 8g LIP)',
                            horario: '08:00:00',
                            id_refeicao: 3619,
                            obs:
                                '<p class="MsoNormal" style="text-align:justify"><span style="font-size: 12pt; line-height: 107%; font-family: "Open Sans", sans-serif; color: rgb(34, 34, 34); background: white;"><span style="background-color: initial; font-size: 12pt; line-height: 107%; color: rgb(77, 77, 77);">Comer sem\npressa, sentado(a), aproveitando o momento, faz uma grande diferença para o\norganismo.</span><span style="font-size: 12pt; line-height: 107%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"> Para conseguir </span><strong style="background-color: initial; color: rgb(102, 102, 102); font-family: "Trebuchet MS", Helvetica, Verdana, sans-serif; font-size: 14px;"><span style="font-size: 12pt; line-height: 107%; font-family: "Open Sans", sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">comer</span></strong><span style="font-size: 12pt; line-height: 107%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"> mais devagar, deve-se\ntentar </span><strong style="background-color: initial; color: rgb(102, 102, 102); font-family: "Trebuchet MS", Helvetica, Verdana, sans-serif; font-size: 14px;"><span style="font-size: 12pt; line-height: 107%; font-family: "Open Sans", sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">comer</span></strong><span style="font-size: 12pt; line-height: 107%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"> sentado à mesa, evitando o sofá ou a cama, evitar o uso de televisão\ndurante a refeição, tente usar sempre talheres para se </span><strong style="background-color: initial; color: rgb(102, 102, 102); font-family: "Trebuchet MS", Helvetica, Verdana, sans-serif; font-size: 14px;"><span style="font-size: 12pt; line-height: 107%; font-family: "Open Sans", sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">alimentar</span></strong><span style="font-size: 12pt; line-height: 107%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"> ao invés de usar as mãos,\nexperimente </span><strong style="background-color: initial; color: rgb(102, 102, 102); font-family: "Trebuchet MS", Helvetica, Verdana, sans-serif; font-size: 14px;"><span style="font-size: 12pt; line-height: 107%; font-family: "Open Sans", sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">consumir</span></strong><span style="font-size: 12pt; line-height: 107%; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"> salada como prato de entrada.</span></span></p><p class="MsoNormal" style="text-align:justify"><span style="font-size:12.0pt;line-height:107%;font-family:"Open Sans","sans-serif";\ncolor:#222222;background:white"><span style="font-size: 12pt; line-height: 107%;"><o:p></o:p></span></span></p>',
                            carboidratos: '20.61',
                            lipideos: '7.99',
                            proteinas: '26.70',
                            kcal: '250.80',
                            pa_refeicao_substituta_alimentos: [
                                {
                                    id: 421,
                                    tabela: 'taco',
                                    id_refeicao: 178,
                                    id_alimento: 58,
                                    medida_caseira: 'Gramas',
                                    gramas: '40.00',
                                    nome: 'Banana, nanica, crua',
                                    quantidade_medida: '40.00',
                                    pa_refeicao_substituta_alimento_equivalentes: [],
                                },
                                {
                                    id: 422,
                                    tabela: 'taco',
                                    id_refeicao: 178,
                                    id_alimento: 1,
                                    medida_caseira: 'Gramas',
                                    gramas: '75.00',
                                    nome: 'Abacate, cru',
                                    quantidade_medida: '75.00',
                                    pa_refeicao_substituta_alimento_equivalentes: [],
                                },
                                {
                                    id: 423,
                                    tabela: 'suplementos',
                                    id_refeicao: 178,
                                    id_alimento: 69,
                                    medida_caseira: 'dosadore(s) cheio(s)',
                                    gramas: '35.00',
                                    nome: 'Best Whey Baunilha',
                                    quantidade_medida: '2.00',
                                    pa_refeicao_substituta_alimento_equivalentes: [],
                                },
                                {
                                    id: 424,
                                    tabela: 'tucunduva',
                                    id_refeicao: 178,
                                    id_alimento: 694,
                                    medida_caseira: 'Gramas',
                                    gramas: '40.00',
                                    nome: 'Morango',
                                    quantidade_medida: '40.00',
                                    pa_refeicao_substituta_alimento_equivalentes: [],
                                },
                            ],
                            pa_refeicao_substituta_alimento_order: {
                                id: 178,
                                id_refeicao_alimento: 178,
                                posicao: 2,
                            },
                        },
                        {
                            id: 183,
                            nome: 'Café da manhã',
                            horario: '07:00:00',
                            id_refeicao: 3619,
                            obs: '',
                            carboidratos: '4.80',
                            lipideos: '15.70',
                            proteinas: '4.30',
                            kcal: '165.90',
                            pa_refeicao_substituta_alimentos: [
                                {
                                    id: 437,
                                    tabela: 'tucunduva',
                                    id_refeicao: 183,
                                    id_alimento: 487,
                                    medida_caseira: 'Colher(es) de sopa',
                                    gramas: '15.00',
                                    nome: 'Iogurte natural',
                                    quantidade_medida: '1.00',
                                    pa_refeicao_substituta_alimento_equivalentes: [],
                                },
                                {
                                    id: 438,
                                    tabela: 'ibge',
                                    id_refeicao: 183,
                                    id_alimento: 164,
                                    medida_caseira: 'Colher(es) de sobremesa',
                                    gramas: '25.00',
                                    nome: 'Avelã',
                                    quantidade_medida: '1.00',
                                    pa_refeicao_substituta_alimento_equivalentes: [],
                                },
                            ],
                            pa_refeicao_substituta_alimento_order: {
                                id: 183,
                                id_refeicao_alimento: 183,
                                posicao: 1,
                            },
                        },
                    ],
                    plano_alimentar_refeicao_order: {
                        id: 3610,
                        id_refeicao: 3619,
                        posicao: 1,
                    },
                },
                {
                    id: 3620,
                    nome: 'Lanche da tarde 1',
                    horario: '15:00:00',
                    id_plano_alimentar: 1090,
                    obs: '',
                    carboidratos: '19.20',
                    lipideos: '7.90',
                    proteinas: '25.80',
                    kcal: '250.60',
                    plano_alimentar_refeicao_alimentos: [
                        {
                            id: 14144,
                            tabela: 'suplementos',
                            id_refeicao: 3620,
                            id_alimento: 69,
                            medida_caseira: 'dosadore(s) cheio(s)',
                            gramas: '26.25',
                            nome: 'Best Whey Baunilha',
                            quantidade_medida: '1.50',
                            plano_alimentar_alimento_equivalentes: [],
                        },
                        {
                            id: 14145,
                            tabela: 'tucunduva',
                            id_refeicao: 3620,
                            id_alimento: 694,
                            medida_caseira: 'Unidade(s) pequenas(s)',
                            gramas: '10.50',
                            nome: 'Morango',
                            quantidade_medida: '1.50',
                            plano_alimentar_alimento_equivalentes: [],
                        },
                        {
                            id: 14146,
                            tabela: 'alimento_customizado',
                            id_refeicao: 3620,
                            id_alimento: 88,
                            medida_caseira: 'Gramas',
                            gramas: '150.00',
                            nome: 'Iogurte Natural Integral (Nestlé)',
                            quantidade_medida: '150.00',
                            plano_alimentar_alimento_equivalentes: [],
                        },
                        {
                            id: 14147,
                            tabela: 'ibge',
                            id_refeicao: 3620,
                            id_alimento: 998,
                            medida_caseira: 'Gramas',
                            gramas: '10.00',
                            nome: 'Granola',
                            quantidade_medida: '10.00',
                            plano_alimentar_alimento_equivalentes: [],
                        },
                    ],
                    pa_refeicao_substituta: [],
                    plano_alimentar_refeicao_order: {
                        id: 3611,
                        id_refeicao: 3620,
                        posicao: 2,
                    },
                },
            ],
            plano_alimentar_refeicao_dias: [
                {
                    id: 784,
                    id_plano_alimentar: 1090,
                    dom: true,
                    seg: true,
                    ter: true,
                    qua: true,
                    qui: true,
                    sex: true,
                    sab: true,
                },
            ],
        },
    ],
    plans_equivalent: [
        {
            id: 224,
            nome: 'Equivalentes ',
            id_paciente: 1333,
            data: '2021-04-02T22:37:40.000Z',
            visivel: 1,
            pae_refeicaos: [
                {
                    id: 638,
                    id_pae: 224,
                    nome: 'Café da manhã',
                    comentario: '',
                    horario: '07:00:00',
                    pae_refeicao_alimentos: [
                        {
                            id: 2430,
                            nome: 'Abadejo, filé, grelhado',
                            quantidade: '1.00',
                            medida_caseira: 'filé(s) pequeno(s)',
                            gramas: '75.00',
                            kcal: '97.50',
                            proteinas: '20.00',
                            carboidratos: '0.00',
                            lipideos: '0.97',
                            id_refeicao: 638,
                            grupo: 'carnes_peixes_aves',
                            is_avulso: 0,
                            id_avulso: null,
                            unidade: '1.00',
                        },
                        {
                            id: 2431,
                            nome: 'Arroz, 7 grãos, cozido ',
                            quantidade: '1.00',
                            medida_caseira: 'colher(es) de sopa rasa(s)',
                            gramas: '15.00',
                            kcal: '50.10',
                            proteinas: '0.70',
                            carboidratos: '5.00',
                            lipideos: '0.00',
                            id_refeicao: 638,
                            grupo: 'graos_tuberculos',
                            is_avulso: 0,
                            id_avulso: null,
                            unidade: '1.00',
                        },
                        {
                            id: 2432,
                            nome: 'Ervilha em grão, cozida',
                            quantidade: '1.00',
                            medida_caseira: 'colher(es) de servir/arroz',
                            gramas: '100.00',
                            kcal: '85.60',
                            proteinas: '4.80',
                            carboidratos: '10.00',
                            lipideos: '3.20',
                            id_refeicao: 638,
                            grupo: 'leguminosas',
                            is_avulso: 0,
                            id_avulso: null,
                            unidade: '2.50',
                        },
                        {
                            id: 2433,
                            nome: 'Azeite, de dendê',
                            quantidade: '1.00',
                            medida_caseira: 'colher(es) de sopa',
                            gramas: '8.00',
                            kcal: '71.00',
                            proteinas: '0.00',
                            carboidratos: '0.00',
                            lipideos: '8.00',
                            id_refeicao: 638,
                            grupo: 'oleos_gorduras',
                            is_avulso: 0,
                            id_avulso: null,
                            unidade: '1.00',
                        },
                        {
                            id: 2434,
                            nome: 'Banana, nanica, crua',
                            quantidade: '1.00',
                            medida_caseira: 'Unidade(s) pequena(s)',
                            gramas: '86.00',
                            kcal: '79.12',
                            proteinas: '1.20',
                            carboidratos: '19.78',
                            lipideos: '0.09',
                            id_refeicao: 638,
                            grupo: 'taco',
                            is_avulso: 1,
                            id_avulso: 58,
                            unidade: null,
                        },
                    ],
                    pae_refeicao_order: {
                        id: 578,
                        id_refeicao: 638,
                        posicao: 1,
                    },
                },
                {
                    id: 639,
                    id_pae: 224,
                    nome: 'Almoço',
                    comentario: '',
                    horario: '12:00:00',
                    pae_refeicao_alimentos: [
                        {
                            id: 2435,
                            nome: 'Abacaxi, cru',
                            quantidade: '1.00',
                            medida_caseira: 'fatia(s) média(s)',
                            gramas: '80.00',
                            kcal: '38.70',
                            proteinas: '0.70',
                            carboidratos: '10.00',
                            lipideos: '0.10',
                            id_refeicao: 639,
                            grupo: 'frutas',
                            is_avulso: 0,
                            id_avulso: null,
                            unidade: '1.00',
                        },
                        {
                            id: 2436,
                            nome: 'Abacate, cru',
                            quantidade: '1.00',
                            medida_caseira: 'colher(es) de sopa cheia(s)',
                            gramas: '99.90',
                            kcal: '96.20',
                            proteinas: '1.20',
                            carboidratos: '6.00',
                            lipideos: '8.00',
                            id_refeicao: 639,
                            grupo: 'frutas_alto_teor_gordura',
                            is_avulso: 0,
                            id_avulso: null,
                            unidade: '2.00',
                        },
                        {
                            id: 2437,
                            nome: 'Coalhada, desnatada',
                            quantidade: '1.00',
                            medida_caseira: 'pote(s)',
                            gramas: '130.00',
                            kcal: '40.00',
                            proteinas: '4.60',
                            carboidratos: '5.50',
                            lipideos: '0.00',
                            id_refeicao: 639,
                            grupo: 'leites_derivados',
                            is_avulso: 0,
                            id_avulso: null,
                            unidade: '1.00',
                        },
                        {
                            id: 2438,
                            nome: 'Acelga, crua',
                            quantidade: '1.00',
                            medida_caseira: 'colher(es) de sopa',
                            gramas: '60.00',
                            kcal: '12.57',
                            proteinas: '0.87',
                            carboidratos: '2.00',
                            lipideos: '0.06',
                            id_refeicao: 639,
                            grupo: 'vegetais_a',
                            is_avulso: 0,
                            id_avulso: null,
                            unidade: '2.00',
                        },
                    ],
                    pae_refeicao_order: {
                        id: 579,
                        id_refeicao: 639,
                        posicao: 2,
                    },
                },
                {
                    id: 640,
                    id_pae: 224,
                    nome: 'Lanche da tarde 1',
                    comentario: '',
                    horario: '15:00:00',
                    pae_refeicao_alimentos: [
                        {
                            id: 2439,
                            nome: 'Abóbora, cabotian, cozida',
                            quantidade: '1.00',
                            medida_caseira: 'colher(es) de sopa',
                            gramas: '20.00',
                            kcal: '11.11',
                            proteinas: '0.29',
                            carboidratos: '2.00',
                            lipideos: '0.15',
                            id_refeicao: 640,
                            grupo: 'vegetais_b',
                            is_avulso: 0,
                            id_avulso: null,
                            unidade: '1.00',
                        },
                        {
                            id: 2440,
                            nome: 'Amêndoa torrada sem sal',
                            quantidade: '1.00',
                            medida_caseira: 'unidade(s)',
                            gramas: '18.00',
                            kcal: '113.90',
                            proteinas: '3.80',
                            carboidratos: '3.30',
                            lipideos: '9.00',
                            id_refeicao: 640,
                            grupo: 'nozes_sementes',
                            is_avulso: 0,
                            id_avulso: null,
                            unidade: '9.90',
                        },
                        {
                            id: 2441,
                            nome: 'Aveia, farelo, crua',
                            quantidade: '1.00',
                            medida_caseira: 'colher(es) de sopa cheia',
                            gramas: '22.00',
                            kcal: '54.12',
                            proteinas: '3.81',
                            carboidratos: '14.57',
                            lipideos: '1.55',
                            id_refeicao: 640,
                            grupo: 'paes_cereais_derivados',
                            is_avulso: 0,
                            id_avulso: null,
                            unidade: '1.00',
                        },
                        {
                            id: 2442,
                            nome: 'Achocolatado, pó',
                            quantidade: '1.00',
                            medida_caseira: 'colher(es) de sopa',
                            gramas: '22.00',
                            kcal: '88.20',
                            proteinas: '0.90',
                            carboidratos: '20.10',
                            lipideos: '0.50',
                            id_refeicao: 640,
                            grupo: 'doces_acucares',
                            is_avulso: 0,
                            id_avulso: null,
                            unidade: '1.00',
                        },
                    ],
                    pae_refeicao_order: {
                        id: 580,
                        id_refeicao: 640,
                        posicao: 3,
                    },
                },
                {
                    id: 641,
                    id_pae: 224,
                    nome: 'Jantar',
                    comentario: '',
                    horario: '18:00:00',
                    pae_refeicao_alimentos: [
                        {
                            id: 2443,
                            nome: 'Chantilly, spray, com gordura vegetal',
                            quantidade: '1.00',
                            medida_caseira: 'colher(es) de sopa',
                            gramas: '30.00',
                            kcal: '94.00',
                            proteinas: '0.00',
                            carboidratos: '5.00',
                            lipideos: '8.00',
                            id_refeicao: 641,
                            grupo: 'altas_calorias',
                            is_avulso: 0,
                            id_avulso: null,
                            unidade: '3.00',
                        },
                        {
                            id: 2444,
                            nome: 'Café, infusão 10%',
                            quantidade: '1.00',
                            medida_caseira: 'xícara(s) de chá',
                            gramas: '100.00',
                            kcal: '9.00',
                            proteinas: '0.70',
                            carboidratos: '1.50',
                            lipideos: '0.10',
                            id_refeicao: 641,
                            grupo: 'baixas_calorias',
                            is_avulso: 0,
                            id_avulso: null,
                            unidade: '0.50',
                        },
                        {
                            id: 2445,
                            nome: 'Albumina',
                            quantidade: '1.00',
                            medida_caseira: 'colher(es) de sopa',
                            gramas: '30.00',
                            kcal: '102.00',
                            proteinas: '23.00',
                            carboidratos: '0.00',
                            lipideos: '0.00',
                            id_refeicao: 641,
                            grupo: 'suplementos_proteicos',
                            is_avulso: 0,
                            id_avulso: null,
                            unidade: '2.00',
                        },
                    ],
                    pae_refeicao_order: {
                        id: 581,
                        id_refeicao: 641,
                        posicao: 4,
                    },
                },
            ],
            pae_refeicao_dias: [
                {
                    id: 92,
                    id_pae: 224,
                    dom: true,
                    seg: true,
                    ter: true,
                    qua: true,
                    qui: true,
                    sex: true,
                    sab: true,
                },
            ],
        },
    ],
}
